name: YouTube Narrative Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # Every day at 2 AM

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run pipeline
        run: python main.py
